name: Update TranslationFiles packages after branch push

# Controls when the workflow will run
on:
    # Trigger only on specific branches
    push:
        branches:
            - integration
            - preproduction
            - master

jobs:
    # Call internal workflow with specified parameters
    automatic_push_archives_to_bucket:
        strategy:
            fail-fast: false
            matrix:
                prestashop_version:
                    - '8.0'
                    - '1.7.8'
        uses: PrestaShop/TranslationFiles/.github/workflows/push_archives_to_bucket.yml@master
        with:
            target_branch: ${{ github.ref_name }}
            prestashop_version: ${{ matrix.prestashop_version }}
        secrets: inherit
