name: Update TranslationFiles packages after branch push

# Controls when the workflow will run
on:
    # Trigger only on specific branches
    push:
        branches:
            - integration
            - preproduction
            - master

jobs:
    # Depending on the branch that triggered this action we are going to switch the environment
    prepare_environment:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        steps:
            - name: Prepare environment to use
              id: branch_check
              run: |
                  if test ${{ github.ref_name }} = "master";
                  then
                    echo "env_name=production" >> $GITHUB_OUTPUT
                  elif test ${{ github.ref_name }} = "preproduction";
                  then
                    echo "env_name=preproduction" >> $GITHUB_OUTPUT
                  else
                    echo "env_name=integration" >> $GITHUB_OUTPUT
                  fi
              shell: bash
        outputs:
            env_name: ${{ steps.branch_check.outputs.env_name }}

    # Call internal workflow with specified parameters
    automatic_push_archives_to_bucket:
        needs: [prepare_environment]
        strategy:
            fail-fast: false
            matrix:
                prestashop_version:
                    - '8.0.x'
                    - '1.7.8.x'
        uses: PrestaShop/TranslationFiles/.github/workflows/push_archives_to_bucket.yml@master
        with:
            environment: ${{ needs.prepare_environment.outputs.env_name }}
            prestashop_version: ${{ matrix.prestashop_version }}
        secrets: inherit
